name: IslandSurvival
version: 1.0
main: com.nonkungch.islandsurvival.IslandSurvival
api-version: 1.21
author: NonKungCh
description: Generates custom island worlds with sharks!
commands:
  createislandworld:
    description: Creates the deserted island (ocean) world.
    usage: /createislandworld
    permission: islandsurvival.createworld
